export const pokemonTypes = [
  { name: 'bug' },
  { name: 'dark' },
  { name: 'dragon' },
  { name: 'electric' },
  { name: 'fairy' },
  { name: 'fighting' },
  { name: 'fire' },
  { name: 'flying' },
  { name: 'ghost' },
  { name: 'grass' },
  { name: 'ground' },
  { name: 'ice' },
  { name: 'normal' },
  { name: 'poison' },
  { name: 'psychic' },
  { name: 'rock' },
  { name: 'steel' },
  { name: 'water' },
]
